version: '3.8'

services:
  postgresql:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: todo_app
    ports:
      - "5433:5432"
    networks:
      - spring-todo-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_todo_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgresql
    networks:
      - spring-todo-network

networks:
  spring-todo-network: